name: Jsonify Csv Data

on:
  push:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: "npm install"
        run: "npm install"

      # Runs a single command using the runners shell
      - name: "Split CSV to JSON Files"
        run: "node index.mjs"

      - name: Commit report
        run: |
          git config --global user.name 'bhandziuk'
          git commit -am "Automated CSV to JSON conversion"
          git push
